### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by BaloghTamas** [nagybalint1993/HsQuiz#1]
Plz, privát repót használj, van hozzá privát Travis is, ne lássák mások!

Az email recipient-et írd át a saját címedre, az én címem csak példaként volt benne, nyilván nem akarok minden failed buildról emailt kapni.

Travis CI doksi utolsó oldalán ott van a Gralde premission gond leírása, azt csináld meg, majd commitold, pushold, és fog fordulni.

Ezt az issuet zárd le!

**Comment by nagybalint1993** [comment]
Elnézést kérek, véletlenül maradt benne a címed.
Nem tudok privát repót használni, mert nekem csak ingyenes accountom van, emiatt lett publikus.

**Comment by BaloghTamas** [comment]
Itt kapsz hallgatói licencet: https://education.github.com/
